/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * BlockUserMutationResponseData
 */
@JsonPropertyOrder({
  BlockUserMutationResponseData.JSON_PROPERTY_BLOCKING
})
@JsonTypeName("BlockUserMutationResponse_data")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class BlockUserMutationResponseData {
    public static final String JSON_PROPERTY_BLOCKING = "blocking";
    private Boolean blocking;

    public BlockUserMutationResponseData() {
    }

    public BlockUserMutationResponseData blocking(Boolean blocking) {
        this.blocking = blocking;
        return this;
    }

    /**
     * Get blocking
     * @return blocking
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_BLOCKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getBlocking() {
        return blocking;
    }

    @JsonProperty(JSON_PROPERTY_BLOCKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBlocking(Boolean blocking) {
        this.blocking = blocking;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BlockUserMutationResponseData blockUserMutationResponseData = (BlockUserMutationResponseData) o;
        return Objects.equals(this.blocking, blockUserMutationResponseData.blocking);
    }

    @Override
    public int hashCode() {
        return Objects.hash(blocking);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BlockUserMutationResponseData {\n");
        sb.append("    blocking: ").append(toIndentedString(blocking)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
