/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.ContextAnnotationDomainFields;
import example.micronaut.model.ContextAnnotationEntityFields;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * Annotation inferred from the Tweet text.
 */
@JsonPropertyOrder({
  ContextAnnotation.JSON_PROPERTY_DOMAIN,
  ContextAnnotation.JSON_PROPERTY_ENTITY
})
@JsonTypeName("ContextAnnotation")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class ContextAnnotation {
    public static final String JSON_PROPERTY_DOMAIN = "domain";
    private ContextAnnotationDomainFields domain;

    public static final String JSON_PROPERTY_ENTITY = "entity";
    private ContextAnnotationEntityFields entity;

    public ContextAnnotation(ContextAnnotationDomainFields domain, ContextAnnotationEntityFields entity) {
        this.domain = domain;
        this.entity = entity;
    }

    public ContextAnnotation domain(ContextAnnotationDomainFields domain) {
        this.domain = domain;
        return this;
    }

    /**
     * Get domain
     * @return domain
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_DOMAIN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public ContextAnnotationDomainFields getDomain() {
        return domain;
    }

    @JsonProperty(JSON_PROPERTY_DOMAIN)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDomain(ContextAnnotationDomainFields domain) {
        this.domain = domain;
    }

    public ContextAnnotation entity(ContextAnnotationEntityFields entity) {
        this.entity = entity;
        return this;
    }

    /**
     * Get entity
     * @return entity
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_ENTITY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public ContextAnnotationEntityFields getEntity() {
        return entity;
    }

    @JsonProperty(JSON_PROPERTY_ENTITY)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEntity(ContextAnnotationEntityFields entity) {
        this.entity = entity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ContextAnnotation contextAnnotation = (ContextAnnotation) o;
        return Objects.equals(this.domain, contextAnnotation.domain) &&
            Objects.equals(this.entity, contextAnnotation.entity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(domain, entity);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ContextAnnotation {\n");
        sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
        sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
