/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * A request to create a new batch compliance job.
 */
@JsonPropertyOrder({
  CreateComplianceJobRequest.JSON_PROPERTY_NAME,
  CreateComplianceJobRequest.JSON_PROPERTY_RESUMABLE,
  CreateComplianceJobRequest.JSON_PROPERTY_TYPE
})
@JsonTypeName("CreateComplianceJobRequest")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class CreateComplianceJobRequest {
    public static final String JSON_PROPERTY_NAME = "name";
    private String name;

    public static final String JSON_PROPERTY_RESUMABLE = "resumable";
    private Boolean resumable;

    /**
     * Type of compliance job to list.
     */
    public enum TypeEnum {
        TWEETS("tweets"),
        USERS("users");

        private String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_TYPE = "type";
    private TypeEnum type;

    public CreateComplianceJobRequest(TypeEnum type) {
        this.type = type;
    }

    public CreateComplianceJobRequest name(String name) {
        this.name = name;
        return this;
    }

    /**
     * User-provided name for a compliance job.
     * @return name
     **/
    @Nullable
    @Size(max=64)
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(String name) {
        this.name = name;
    }

    public CreateComplianceJobRequest resumable(Boolean resumable) {
        this.resumable = resumable;
        return this;
    }

    /**
     * If true, this endpoint will return a pre-signed URL with resumable uploads enabled.
     * @return resumable
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_RESUMABLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getResumable() {
        return resumable;
    }

    @JsonProperty(JSON_PROPERTY_RESUMABLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResumable(Boolean resumable) {
        this.resumable = resumable;
    }

    public CreateComplianceJobRequest type(TypeEnum type) {
        this.type = type;
        return this;
    }

    /**
     * Type of compliance job to list.
     * @return type
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TypeEnum getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setType(TypeEnum type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateComplianceJobRequest createComplianceJobRequest = (CreateComplianceJobRequest) o;
        return Objects.equals(this.name, createComplianceJobRequest.name) &&
            Objects.equals(this.resumable, createComplianceJobRequest.resumable) &&
            Objects.equals(this.type, createComplianceJobRequest.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, resumable, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateComplianceJobRequest {\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    resumable: ").append(toIndentedString(resumable)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
