/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * Annotation for entities based on the Tweet text.
 */
@JsonPropertyOrder({
  FullTextEntitiesAnnotationsInner.JSON_PROPERTY_END,
  FullTextEntitiesAnnotationsInner.JSON_PROPERTY_START,
  FullTextEntitiesAnnotationsInner.JSON_PROPERTY_NORMALIZED_TEXT,
  FullTextEntitiesAnnotationsInner.JSON_PROPERTY_PROBABILITY,
  FullTextEntitiesAnnotationsInner.JSON_PROPERTY_TYPE
})
@JsonTypeName("FullTextEntities_annotations_inner")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class FullTextEntitiesAnnotationsInner {
    public static final String JSON_PROPERTY_END = "end";
    private Integer end;

    public static final String JSON_PROPERTY_START = "start";
    private Integer start;

    public static final String JSON_PROPERTY_NORMALIZED_TEXT = "normalized_text";
    private String normalizedText;

    public static final String JSON_PROPERTY_PROBABILITY = "probability";
    private Double probability;

    public static final String JSON_PROPERTY_TYPE = "type";
    private String type;

    public FullTextEntitiesAnnotationsInner(Integer end, Integer start) {
        this.end = end;
        this.start = start;
    }

    public FullTextEntitiesAnnotationsInner end(Integer end) {
        this.end = end;
        return this;
    }

    /**
     * Index (zero-based) at which position this entity ends.  The index is inclusive.
     * minimum: 0
     * @return end
     **/
    @NotNull
    @Min(0)
    @JsonProperty(JSON_PROPERTY_END)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getEnd() {
        return end;
    }

    @JsonProperty(JSON_PROPERTY_END)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEnd(Integer end) {
        this.end = end;
    }

    public FullTextEntitiesAnnotationsInner start(Integer start) {
        this.start = start;
        return this;
    }

    /**
     * Index (zero-based) at which position this entity starts.  The index is inclusive.
     * minimum: 0
     * @return start
     **/
    @NotNull
    @Min(0)
    @JsonProperty(JSON_PROPERTY_START)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getStart() {
        return start;
    }

    @JsonProperty(JSON_PROPERTY_START)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setStart(Integer start) {
        this.start = start;
    }

    public FullTextEntitiesAnnotationsInner normalizedText(String normalizedText) {
        this.normalizedText = normalizedText;
        return this;
    }

    /**
     * Text used to determine annotation.
     * @return normalizedText
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_NORMALIZED_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getNormalizedText() {
        return normalizedText;
    }

    @JsonProperty(JSON_PROPERTY_NORMALIZED_TEXT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNormalizedText(String normalizedText) {
        this.normalizedText = normalizedText;
    }

    public FullTextEntitiesAnnotationsInner probability(Double probability) {
        this.probability = probability;
        return this;
    }

    /**
     * Confidence factor for annotation type.
     * minimum: 0
     * maximum: 1
     * @return probability
     **/
    @Nullable
    @DecimalMin("0")
    @DecimalMax("1")
    @JsonProperty(JSON_PROPERTY_PROBABILITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Double getProbability() {
        return probability;
    }

    @JsonProperty(JSON_PROPERTY_PROBABILITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProbability(Double probability) {
        this.probability = probability;
    }

    public FullTextEntitiesAnnotationsInner type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Annotation type.
     * @return type
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(String type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        FullTextEntitiesAnnotationsInner fullTextEntitiesAnnotationsInner = (FullTextEntitiesAnnotationsInner) o;
        return Objects.equals(this.end, fullTextEntitiesAnnotationsInner.end) &&
            Objects.equals(this.start, fullTextEntitiesAnnotationsInner.start) &&
            Objects.equals(this.normalizedText, fullTextEntitiesAnnotationsInner.normalizedText) &&
            Objects.equals(this.probability, fullTextEntitiesAnnotationsInner.probability) &&
            Objects.equals(this.type, fullTextEntitiesAnnotationsInner.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(end, start, normalizedText, probability, type);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class FullTextEntitiesAnnotationsInner {\n");
        sb.append("    end: ").append(toIndentedString(end)).append("\n");
        sb.append("    start: ").append(toIndentedString(start)).append("\n");
        sb.append("    normalizedText: ").append(toIndentedString(normalizedText)).append("\n");
        sb.append("    probability: ").append(toIndentedString(probability)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
