/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * Get2TweetsIdQuoteTweetsResponseMeta
 */
@JsonPropertyOrder({
  Get2TweetsIdQuoteTweetsResponseMeta.JSON_PROPERTY_NEXT_TOKEN,
  Get2TweetsIdQuoteTweetsResponseMeta.JSON_PROPERTY_RESULT_COUNT
})
@JsonTypeName("Get2TweetsIdQuoteTweetsResponse_meta")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class Get2TweetsIdQuoteTweetsResponseMeta {
    public static final String JSON_PROPERTY_NEXT_TOKEN = "next_token";
    private String nextToken;

    public static final String JSON_PROPERTY_RESULT_COUNT = "result_count";
    private Integer resultCount;

    public Get2TweetsIdQuoteTweetsResponseMeta() {
    }

    public Get2TweetsIdQuoteTweetsResponseMeta nextToken(String nextToken) {
        this.nextToken = nextToken;
        return this;
    }

    /**
     * The next token.
     * @return nextToken
     **/
    @Nullable
    @Size(min=1)
    @JsonProperty(JSON_PROPERTY_NEXT_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getNextToken() {
        return nextToken;
    }

    @JsonProperty(JSON_PROPERTY_NEXT_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNextToken(String nextToken) {
        this.nextToken = nextToken;
    }

    public Get2TweetsIdQuoteTweetsResponseMeta resultCount(Integer resultCount) {
        this.resultCount = resultCount;
        return this;
    }

    /**
     * The number of results returned in this response.
     * @return resultCount
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_RESULT_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getResultCount() {
        return resultCount;
    }

    @JsonProperty(JSON_PROPERTY_RESULT_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResultCount(Integer resultCount) {
        this.resultCount = resultCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Get2TweetsIdQuoteTweetsResponseMeta get2TweetsIdQuoteTweetsResponseMeta = (Get2TweetsIdQuoteTweetsResponseMeta) o;
        return Objects.equals(this.nextToken, get2TweetsIdQuoteTweetsResponseMeta.nextToken) &&
            Objects.equals(this.resultCount, get2TweetsIdQuoteTweetsResponseMeta.resultCount);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nextToken, resultCount);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Get2TweetsIdQuoteTweetsResponseMeta {\n");
        sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
        sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
