/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.InvalidRequestProblemAllOfErrors;
import example.micronaut.model.Problem;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * A problem that indicates this request is invalid.
 */
@JsonPropertyOrder({
  InvalidRequestProblem.JSON_PROPERTY_ERRORS
})
@JsonTypeName("InvalidRequestProblem")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class InvalidRequestProblem extends Problem {
    public static final String JSON_PROPERTY_ERRORS = "errors";
    private List<InvalidRequestProblemAllOfErrors> errors = null;

    public InvalidRequestProblem(String title, String type) {
        super(title, type);
    }

    public InvalidRequestProblem errors(List<InvalidRequestProblemAllOfErrors> errors) {
        this.errors = errors;
        return this;
    }

    public InvalidRequestProblem addErrorsItem(InvalidRequestProblemAllOfErrors errorsItem) {
        if (this.errors == null) {
            this.errors = new ArrayList<>();
        }
        this.errors.add(errorsItem);
        return this;
    }

    /**
     * Get errors
     * @return errors
     **/
    @Nullable
    @Size(min=1)
    @JsonProperty(JSON_PROPERTY_ERRORS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public List<InvalidRequestProblemAllOfErrors> getErrors() {
        return errors;
    }

    @JsonProperty(JSON_PROPERTY_ERRORS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setErrors(List<InvalidRequestProblemAllOfErrors> errors) {
        this.errors = errors;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        InvalidRequestProblem invalidRequestProblem = (InvalidRequestProblem) o;
        return Objects.equals(this.errors, invalidRequestProblem.errors) &&
            super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(errors, super.hashCode());
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class InvalidRequestProblem {\n");
        sb.append("    ").append(toIndentedString(super.toString())).append("\n");
        sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
