/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * ListPinnedResponseData
 */
@JsonPropertyOrder({
  ListPinnedResponseData.JSON_PROPERTY_PINNED
})
@JsonTypeName("ListPinnedResponse_data")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class ListPinnedResponseData {
    public static final String JSON_PROPERTY_PINNED = "pinned";
    private Boolean pinned;

    public ListPinnedResponseData() {
    }

    public ListPinnedResponseData pinned(Boolean pinned) {
        this.pinned = pinned;
        return this;
    }

    /**
     * Get pinned
     * @return pinned
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PINNED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getPinned() {
        return pinned;
    }

    @JsonProperty(JSON_PROPERTY_PINNED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPinned(Boolean pinned) {
        this.pinned = pinned;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListPinnedResponseData listPinnedResponseData = (ListPinnedResponseData) o;
        return Objects.equals(this.pinned, listPinnedResponseData.pinned);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pinned);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ListPinnedResponseData {\n");
        sb.append("    pinned: ").append(toIndentedString(pinned)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
