/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * MuteUserMutationResponseData
 */
@JsonPropertyOrder({
  MuteUserMutationResponseData.JSON_PROPERTY_MUTING
})
@JsonTypeName("MuteUserMutationResponse_data")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class MuteUserMutationResponseData {
    public static final String JSON_PROPERTY_MUTING = "muting";
    private Boolean muting;

    public MuteUserMutationResponseData() {
    }

    public MuteUserMutationResponseData muting(Boolean muting) {
        this.muting = muting;
        return this;
    }

    /**
     * Get muting
     * @return muting
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_MUTING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getMuting() {
        return muting;
    }

    @JsonProperty(JSON_PROPERTY_MUTING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMuting(Boolean muting) {
        this.muting = muting;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MuteUserMutationResponseData muteUserMutationResponseData = (MuteUserMutationResponseData) o;
        return Objects.equals(this.muting, muteUserMutationResponseData.muting);
    }

    @Override
    public int hashCode() {
        return Objects.hash(muting);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MuteUserMutationResponseData {\n");
        sb.append("    muting: ").append(toIndentedString(muting)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
