/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.RulesRequestSummaryOneOf;
import example.micronaut.model.RulesRequestSummaryOneOf1;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * RulesRequestSummary
 */
@JsonPropertyOrder({
  RulesRequestSummary.JSON_PROPERTY_CREATED,
  RulesRequestSummary.JSON_PROPERTY_INVALID,
  RulesRequestSummary.JSON_PROPERTY_NOT_CREATED,
  RulesRequestSummary.JSON_PROPERTY_VALID,
  RulesRequestSummary.JSON_PROPERTY_DELETED,
  RulesRequestSummary.JSON_PROPERTY_NOT_DELETED
})
@JsonTypeName("RulesRequestSummary")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class RulesRequestSummary {
    public static final String JSON_PROPERTY_CREATED = "created";
    private Integer created;

    public static final String JSON_PROPERTY_INVALID = "invalid";
    private Integer invalid;

    public static final String JSON_PROPERTY_NOT_CREATED = "not_created";
    private Integer notCreated;

    public static final String JSON_PROPERTY_VALID = "valid";
    private Integer valid;

    public static final String JSON_PROPERTY_DELETED = "deleted";
    private Integer deleted;

    public static final String JSON_PROPERTY_NOT_DELETED = "not_deleted";
    private Integer notDeleted;

    public RulesRequestSummary(Integer created, Integer invalid, Integer notCreated, Integer valid, Integer deleted, Integer notDeleted) {
        this.created = created;
        this.invalid = invalid;
        this.notCreated = notCreated;
        this.valid = valid;
        this.deleted = deleted;
        this.notDeleted = notDeleted;
    }

    public RulesRequestSummary created(Integer created) {
        this.created = created;
        return this;
    }

    /**
     * Number of user-specified stream filtering rules that were created.
     * @return created
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_CREATED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getCreated() {
        return created;
    }

    @JsonProperty(JSON_PROPERTY_CREATED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setCreated(Integer created) {
        this.created = created;
    }

    public RulesRequestSummary invalid(Integer invalid) {
        this.invalid = invalid;
        return this;
    }

    /**
     * Number of invalid user-specified stream filtering rules.
     * @return invalid
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_INVALID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getInvalid() {
        return invalid;
    }

    @JsonProperty(JSON_PROPERTY_INVALID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setInvalid(Integer invalid) {
        this.invalid = invalid;
    }

    public RulesRequestSummary notCreated(Integer notCreated) {
        this.notCreated = notCreated;
        return this;
    }

    /**
     * Number of user-specified stream filtering rules that were not created.
     * @return notCreated
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_NOT_CREATED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getNotCreated() {
        return notCreated;
    }

    @JsonProperty(JSON_PROPERTY_NOT_CREATED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNotCreated(Integer notCreated) {
        this.notCreated = notCreated;
    }

    public RulesRequestSummary valid(Integer valid) {
        this.valid = valid;
        return this;
    }

    /**
     * Number of valid user-specified stream filtering rules.
     * @return valid
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_VALID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getValid() {
        return valid;
    }

    @JsonProperty(JSON_PROPERTY_VALID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setValid(Integer valid) {
        this.valid = valid;
    }

    public RulesRequestSummary deleted(Integer deleted) {
        this.deleted = deleted;
        return this;
    }

    /**
     * Number of user-specified stream filtering rules that were deleted.
     * @return deleted
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_DELETED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getDeleted() {
        return deleted;
    }

    @JsonProperty(JSON_PROPERTY_DELETED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public RulesRequestSummary notDeleted(Integer notDeleted) {
        this.notDeleted = notDeleted;
        return this;
    }

    /**
     * Number of user-specified stream filtering rules that were not deleted.
     * @return notDeleted
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_NOT_DELETED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public Integer getNotDeleted() {
        return notDeleted;
    }

    @JsonProperty(JSON_PROPERTY_NOT_DELETED)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setNotDeleted(Integer notDeleted) {
        this.notDeleted = notDeleted;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RulesRequestSummary rulesRequestSummary = (RulesRequestSummary) o;
        return Objects.equals(this.created, rulesRequestSummary.created) &&
            Objects.equals(this.invalid, rulesRequestSummary.invalid) &&
            Objects.equals(this.notCreated, rulesRequestSummary.notCreated) &&
            Objects.equals(this.valid, rulesRequestSummary.valid) &&
            Objects.equals(this.deleted, rulesRequestSummary.deleted) &&
            Objects.equals(this.notDeleted, rulesRequestSummary.notDeleted);
    }

    @Override
    public int hashCode() {
        return Objects.hash(created, invalid, notCreated, valid, deleted, notDeleted);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RulesRequestSummary {\n");
        sb.append("    created: ").append(toIndentedString(created)).append("\n");
        sb.append("    invalid: ").append(toIndentedString(invalid)).append("\n");
        sb.append("    notCreated: ").append(toIndentedString(notCreated)).append("\n");
        sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
        sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
        sb.append("    notDeleted: ").append(toIndentedString(notDeleted)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
