/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.RulesRequestSummary;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * RulesResponseMetadata
 */
@JsonPropertyOrder({
  RulesResponseMetadata.JSON_PROPERTY_NEXT_TOKEN,
  RulesResponseMetadata.JSON_PROPERTY_RESULT_COUNT,
  RulesResponseMetadata.JSON_PROPERTY_SENT,
  RulesResponseMetadata.JSON_PROPERTY_SUMMARY
})
@JsonTypeName("RulesResponseMetadata")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class RulesResponseMetadata {
    public static final String JSON_PROPERTY_NEXT_TOKEN = "next_token";
    private String nextToken;

    public static final String JSON_PROPERTY_RESULT_COUNT = "result_count";
    private Integer resultCount;

    public static final String JSON_PROPERTY_SENT = "sent";
    private String sent;

    public static final String JSON_PROPERTY_SUMMARY = "summary";
    private RulesRequestSummary summary;

    public RulesResponseMetadata(String sent) {
        this.sent = sent;
    }

    public RulesResponseMetadata nextToken(String nextToken) {
        this.nextToken = nextToken;
        return this;
    }

    /**
     * The next token.
     * @return nextToken
     **/
    @Nullable
    @Size(min=1)
    @JsonProperty(JSON_PROPERTY_NEXT_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getNextToken() {
        return nextToken;
    }

    @JsonProperty(JSON_PROPERTY_NEXT_TOKEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNextToken(String nextToken) {
        this.nextToken = nextToken;
    }

    public RulesResponseMetadata resultCount(Integer resultCount) {
        this.resultCount = resultCount;
        return this;
    }

    /**
     * Number of Rules in result set.
     * @return resultCount
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_RESULT_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getResultCount() {
        return resultCount;
    }

    @JsonProperty(JSON_PROPERTY_RESULT_COUNT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResultCount(Integer resultCount) {
        this.resultCount = resultCount;
    }

    public RulesResponseMetadata sent(String sent) {
        this.sent = sent;
        return this;
    }

    /**
     * Get sent
     * @return sent
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_SENT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getSent() {
        return sent;
    }

    @JsonProperty(JSON_PROPERTY_SENT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setSent(String sent) {
        this.sent = sent;
    }

    public RulesResponseMetadata summary(RulesRequestSummary summary) {
        this.summary = summary;
        return this;
    }

    /**
     * Get summary
     * @return summary
     **/
    @Valid
    @Nullable
    @JsonProperty(JSON_PROPERTY_SUMMARY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public RulesRequestSummary getSummary() {
        return summary;
    }

    @JsonProperty(JSON_PROPERTY_SUMMARY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSummary(RulesRequestSummary summary) {
        this.summary = summary;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RulesResponseMetadata rulesResponseMetadata = (RulesResponseMetadata) o;
        return Objects.equals(this.nextToken, rulesResponseMetadata.nextToken) &&
            Objects.equals(this.resultCount, rulesResponseMetadata.resultCount) &&
            Objects.equals(this.sent, rulesResponseMetadata.sent) &&
            Objects.equals(this.summary, rulesResponseMetadata.summary);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nextToken, resultCount, sent, summary);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RulesResponseMetadata {\n");
        sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
        sb.append("    resultCount: ").append(toIndentedString(resultCount)).append("\n");
        sb.append("    sent: ").append(toIndentedString(sent)).append("\n");
        sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
