/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.TweetComplianceSchema;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * TweetUndropComplianceSchema
 */
@JsonPropertyOrder({
  TweetUndropComplianceSchema.JSON_PROPERTY_UNDROP
})
@JsonTypeName("TweetUndropComplianceSchema")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class TweetUndropComplianceSchema {
    public static final String JSON_PROPERTY_UNDROP = "undrop";
    private TweetComplianceSchema undrop;

    public TweetUndropComplianceSchema(TweetComplianceSchema undrop) {
        this.undrop = undrop;
    }

    public TweetUndropComplianceSchema undrop(TweetComplianceSchema undrop) {
        this.undrop = undrop;
        return this;
    }

    /**
     * Get undrop
     * @return undrop
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_UNDROP)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TweetComplianceSchema getUndrop() {
        return undrop;
    }

    @JsonProperty(JSON_PROPERTY_UNDROP)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUndrop(TweetComplianceSchema undrop) {
        this.undrop = undrop;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TweetUndropComplianceSchema tweetUndropComplianceSchema = (TweetUndropComplianceSchema) o;
        return Objects.equals(this.undrop, tweetUndropComplianceSchema.undrop);
    }

    @Override
    public int hashCode() {
        return Objects.hash(undrop);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TweetUndropComplianceSchema {\n");
        sb.append("    undrop: ").append(toIndentedString(undrop)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
