/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import example.micronaut.model.Point;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * The location tagged on the Tweet, if the user provided one.
 */
@JsonPropertyOrder({
  TweetGeo.JSON_PROPERTY_COORDINATES,
  TweetGeo.JSON_PROPERTY_PLACE_ID
})
@JsonTypeName("Tweet_geo")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class TweetGeo {
    public static final String JSON_PROPERTY_COORDINATES = "coordinates";
    private Point coordinates;

    public static final String JSON_PROPERTY_PLACE_ID = "place_id";
    private String placeId;

    public TweetGeo() {
    }

    public TweetGeo coordinates(Point coordinates) {
        this.coordinates = coordinates;
        return this;
    }

    /**
     * Get coordinates
     * @return coordinates
     **/
    @Valid
    @Nullable
    @JsonProperty(JSON_PROPERTY_COORDINATES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Point getCoordinates() {
        return coordinates;
    }

    @JsonProperty(JSON_PROPERTY_COORDINATES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCoordinates(Point coordinates) {
        this.coordinates = coordinates;
    }

    public TweetGeo placeId(String placeId) {
        this.placeId = placeId;
        return this;
    }

    /**
     * The identifier for this place.
     * @return placeId
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PLACE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getPlaceId() {
        return placeId;
    }

    @JsonProperty(JSON_PROPERTY_PLACE_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlaceId(String placeId) {
        this.placeId = placeId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TweetGeo tweetGeo = (TweetGeo) o;
        return Objects.equals(this.coordinates, tweetGeo.coordinates) &&
            Objects.equals(this.placeId, tweetGeo.placeId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(coordinates, placeId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TweetGeo {\n");
        sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
        sb.append("    placeId: ").append(toIndentedString(placeId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
