/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * TweetComplianceSchemaTweet
 */
@JsonPropertyOrder({
  TweetComplianceSchemaTweet.JSON_PROPERTY_AUTHOR_ID,
  TweetComplianceSchemaTweet.JSON_PROPERTY_ID
})
@JsonTypeName("TweetComplianceSchema_tweet")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class TweetComplianceSchemaTweet {
    public static final String JSON_PROPERTY_AUTHOR_ID = "author_id";
    private String authorId;

    public static final String JSON_PROPERTY_ID = "id";
    private String id;

    public TweetComplianceSchemaTweet(String authorId, String id) {
        this.authorId = authorId;
        this.id = id;
    }

    public TweetComplianceSchemaTweet authorId(String authorId) {
        this.authorId = authorId;
        return this;
    }

    /**
     * Unique identifier of this User. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @return authorId
     **/
    @NotNull
    @Pattern(regexp="^[0-9]{1,19}$")
    @JsonProperty(JSON_PROPERTY_AUTHOR_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getAuthorId() {
        return authorId;
    }

    @JsonProperty(JSON_PROPERTY_AUTHOR_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    public TweetComplianceSchemaTweet id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @return id
     **/
    @NotNull
    @Pattern(regexp="^[0-9]{1,19}$")
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TweetComplianceSchemaTweet tweetComplianceSchemaTweet = (TweetComplianceSchemaTweet) o;
        return Objects.equals(this.authorId, tweetComplianceSchemaTweet.authorId) &&
            Objects.equals(this.id, tweetComplianceSchemaTweet.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(authorId, id);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TweetComplianceSchemaTweet {\n");
        sb.append("    authorId: ").append(toIndentedString(authorId)).append("\n");
        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
