/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.TweetComplianceSchemaTweet;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * TweetNotice
 */
@JsonPropertyOrder({
  TweetNotice.JSON_PROPERTY_APPLICATION,
  TweetNotice.JSON_PROPERTY_DETAILS,
  TweetNotice.JSON_PROPERTY_EVENT_AT,
  TweetNotice.JSON_PROPERTY_EVENT_TYPE,
  TweetNotice.JSON_PROPERTY_EXTENDED_DETAILS_URL,
  TweetNotice.JSON_PROPERTY_LABEL_TITLE,
  TweetNotice.JSON_PROPERTY_TWEET
})
@JsonTypeName("TweetNotice")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class TweetNotice {
    public static final String JSON_PROPERTY_APPLICATION = "application";
    private String _application;

    public static final String JSON_PROPERTY_DETAILS = "details";
    private String details;

    public static final String JSON_PROPERTY_EVENT_AT = "event_at";
    private OffsetDateTime eventAt;

    public static final String JSON_PROPERTY_EVENT_TYPE = "event_type";
    private String eventType;

    public static final String JSON_PROPERTY_EXTENDED_DETAILS_URL = "extended_details_url";
    private String extendedDetailsUrl;

    public static final String JSON_PROPERTY_LABEL_TITLE = "label_title";
    private String labelTitle;

    public static final String JSON_PROPERTY_TWEET = "tweet";
    private TweetComplianceSchemaTweet tweet;

    public TweetNotice(String _application, OffsetDateTime eventAt, String eventType, TweetComplianceSchemaTweet tweet) {
        this._application = _application;
        this.eventAt = eventAt;
        this.eventType = eventType;
        this.tweet = tweet;
    }

    public TweetNotice _application(String _application) {
        this._application = _application;
        return this;
    }

    /**
     * If the label is being applied or removed. Possible values are ‘apply’ or ‘remove’.
     * @return _application
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_APPLICATION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getApplication() {
        return _application;
    }

    @JsonProperty(JSON_PROPERTY_APPLICATION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setApplication(String _application) {
        this._application = _application;
    }

    public TweetNotice details(String details) {
        this.details = details;
        return this;
    }

    /**
     * Information shown on the Tweet label
     * @return details
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_DETAILS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getDetails() {
        return details;
    }

    @JsonProperty(JSON_PROPERTY_DETAILS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDetails(String details) {
        this.details = details;
    }

    public TweetNotice eventAt(OffsetDateTime eventAt) {
        this.eventAt = eventAt;
        return this;
    }

    /**
     * Event time.
     * @return eventAt
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_EVENT_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getEventAt() {
        return eventAt;
    }

    @JsonProperty(JSON_PROPERTY_EVENT_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setEventAt(OffsetDateTime eventAt) {
        this.eventAt = eventAt;
    }

    public TweetNotice eventType(String eventType) {
        this.eventType = eventType;
        return this;
    }

    /**
     * The type of label on the Tweet
     * @return eventType
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getEventType() {
        return eventType;
    }

    @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public TweetNotice extendedDetailsUrl(String extendedDetailsUrl) {
        this.extendedDetailsUrl = extendedDetailsUrl;
        return this;
    }

    /**
     * Link to more information about this kind of label
     * @return extendedDetailsUrl
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_EXTENDED_DETAILS_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getExtendedDetailsUrl() {
        return extendedDetailsUrl;
    }

    @JsonProperty(JSON_PROPERTY_EXTENDED_DETAILS_URL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExtendedDetailsUrl(String extendedDetailsUrl) {
        this.extendedDetailsUrl = extendedDetailsUrl;
    }

    public TweetNotice labelTitle(String labelTitle) {
        this.labelTitle = labelTitle;
        return this;
    }

    /**
     * Title/header of the Tweet label
     * @return labelTitle
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_LABEL_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public String getLabelTitle() {
        return labelTitle;
    }

    @JsonProperty(JSON_PROPERTY_LABEL_TITLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLabelTitle(String labelTitle) {
        this.labelTitle = labelTitle;
    }

    public TweetNotice tweet(TweetComplianceSchemaTweet tweet) {
        this.tweet = tweet;
        return this;
    }

    /**
     * Get tweet
     * @return tweet
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_TWEET)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public TweetComplianceSchemaTweet getTweet() {
        return tweet;
    }

    @JsonProperty(JSON_PROPERTY_TWEET)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTweet(TweetComplianceSchemaTweet tweet) {
        this.tweet = tweet;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TweetNotice tweetNotice = (TweetNotice) o;
        return Objects.equals(this._application, tweetNotice._application) &&
            Objects.equals(this.details, tweetNotice.details) &&
            Objects.equals(this.eventAt, tweetNotice.eventAt) &&
            Objects.equals(this.eventType, tweetNotice.eventType) &&
            Objects.equals(this.extendedDetailsUrl, tweetNotice.extendedDetailsUrl) &&
            Objects.equals(this.labelTitle, tweetNotice.labelTitle) &&
            Objects.equals(this.tweet, tweetNotice.tweet);
    }

    @Override
    public int hashCode() {
        return Objects.hash(_application, details, eventAt, eventType, extendedDetailsUrl, labelTitle, tweet);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TweetNotice {\n");
        sb.append("    _application: ").append(toIndentedString(_application)).append("\n");
        sb.append("    details: ").append(toIndentedString(details)).append("\n");
        sb.append("    eventAt: ").append(toIndentedString(eventAt)).append("\n");
        sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
        sb.append("    extendedDetailsUrl: ").append(toIndentedString(extendedDetailsUrl)).append("\n");
        sb.append("    labelTitle: ").append(toIndentedString(labelTitle)).append("\n");
        sb.append("    tweet: ").append(toIndentedString(tweet)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
