/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UsageCapExceededProblemAllOf
 */
@JsonPropertyOrder({
  UsageCapExceededProblemAllOf.JSON_PROPERTY_PERIOD,
  UsageCapExceededProblemAllOf.JSON_PROPERTY_SCOPE
})
@JsonTypeName("UsageCapExceededProblem_allOf")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UsageCapExceededProblemAllOf {
    /**
     * Gets or Sets period
     */
    public enum PeriodEnum {
        DAILY("Daily"),
        MONTHLY("Monthly");

        private String value;

        PeriodEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static PeriodEnum fromValue(String value) {
            for (PeriodEnum b : PeriodEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_PERIOD = "period";
    private PeriodEnum period;

    /**
     * Gets or Sets scope
     */
    public enum ScopeEnum {
        ACCOUNT("Account"),
        PRODUCT("Product");

        private String value;

        ScopeEnum(String value) {
            this.value = value;
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        @JsonCreator
        public static ScopeEnum fromValue(String value) {
            for (ScopeEnum b : ScopeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
    }
    public static final String JSON_PROPERTY_SCOPE = "scope";
    private ScopeEnum scope;

    public UsageCapExceededProblemAllOf() {
    }

    public UsageCapExceededProblemAllOf period(PeriodEnum period) {
        this.period = period;
        return this;
    }

    /**
     * Get period
     * @return period
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PERIOD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public PeriodEnum getPeriod() {
        return period;
    }

    @JsonProperty(JSON_PROPERTY_PERIOD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPeriod(PeriodEnum period) {
        this.period = period;
    }

    public UsageCapExceededProblemAllOf scope(ScopeEnum scope) {
        this.scope = scope;
        return this;
    }

    /**
     * Get scope
     * @return scope
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_SCOPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public ScopeEnum getScope() {
        return scope;
    }

    @JsonProperty(JSON_PROPERTY_SCOPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setScope(ScopeEnum scope) {
        this.scope = scope;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UsageCapExceededProblemAllOf usageCapExceededProblemAllOf = (UsageCapExceededProblemAllOf) o;
        return Objects.equals(this.period, usageCapExceededProblemAllOf.period) &&
            Objects.equals(this.scope, usageCapExceededProblemAllOf.scope);
    }

    @Override
    public int hashCode() {
        return Objects.hash(period, scope);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UsageCapExceededProblemAllOf {\n");
        sb.append("    period: ").append(toIndentedString(period)).append("\n");
        sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
