/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UsersRetweetsCreateResponseData
 */
@JsonPropertyOrder({
  UsersRetweetsCreateResponseData.JSON_PROPERTY_RETWEETED
})
@JsonTypeName("UsersRetweetsCreateResponse_data")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UsersRetweetsCreateResponseData {
    public static final String JSON_PROPERTY_RETWEETED = "retweeted";
    private Boolean retweeted;

    public UsersRetweetsCreateResponseData() {
    }

    public UsersRetweetsCreateResponseData retweeted(Boolean retweeted) {
        this.retweeted = retweeted;
        return this;
    }

    /**
     * Get retweeted
     * @return retweeted
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_RETWEETED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getRetweeted() {
        return retweeted;
    }

    @JsonProperty(JSON_PROPERTY_RETWEETED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRetweeted(Boolean retweeted) {
        this.retweeted = retweeted;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UsersRetweetsCreateResponseData usersRetweetsCreateResponseData = (UsersRetweetsCreateResponseData) o;
        return Objects.equals(this.retweeted, usersRetweetsCreateResponseData.retweeted);
    }

    @Override
    public int hashCode() {
        return Objects.hash(retweeted);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UsersRetweetsCreateResponseData {\n");
        sb.append("    retweeted: ").append(toIndentedString(retweeted)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
