/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UsersLikesCreateRequest
 */
@JsonPropertyOrder({
  UsersLikesCreateRequest.JSON_PROPERTY_TWEET_ID
})
@JsonTypeName("UsersLikesCreateRequest")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UsersLikesCreateRequest {
    public static final String JSON_PROPERTY_TWEET_ID = "tweet_id";
    private String tweetId;

    public UsersLikesCreateRequest(String tweetId) {
        this.tweetId = tweetId;
    }

    public UsersLikesCreateRequest tweetId(String tweetId) {
        this.tweetId = tweetId;
        return this;
    }

    /**
     * Unique identifier of this Tweet. This is returned as a string in order to avoid complications with languages and tools that cannot handle large integers.
     * @return tweetId
     **/
    @NotNull
    @Pattern(regexp="^[0-9]{1,19}$")
    @JsonProperty(JSON_PROPERTY_TWEET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public String getTweetId() {
        return tweetId;
    }

    @JsonProperty(JSON_PROPERTY_TWEET_ID)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setTweetId(String tweetId) {
        this.tweetId = tweetId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UsersLikesCreateRequest usersLikesCreateRequest = (UsersLikesCreateRequest) o;
        return Objects.equals(this.tweetId, usersLikesCreateRequest.tweetId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tweetId);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UsersLikesCreateRequest {\n");
        sb.append("    tweetId: ").append(toIndentedString(tweetId)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
