/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UsersFollowingCreateResponseData
 */
@JsonPropertyOrder({
  UsersFollowingCreateResponseData.JSON_PROPERTY_FOLLOWING,
  UsersFollowingCreateResponseData.JSON_PROPERTY_PENDING_FOLLOW
})
@JsonTypeName("UsersFollowingCreateResponse_data")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UsersFollowingCreateResponseData {
    public static final String JSON_PROPERTY_FOLLOWING = "following";
    private Boolean following;

    public static final String JSON_PROPERTY_PENDING_FOLLOW = "pending_follow";
    private Boolean pendingFollow;

    public UsersFollowingCreateResponseData() {
    }

    public UsersFollowingCreateResponseData following(Boolean following) {
        this.following = following;
        return this;
    }

    /**
     * Get following
     * @return following
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_FOLLOWING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getFollowing() {
        return following;
    }

    @JsonProperty(JSON_PROPERTY_FOLLOWING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFollowing(Boolean following) {
        this.following = following;
    }

    public UsersFollowingCreateResponseData pendingFollow(Boolean pendingFollow) {
        this.pendingFollow = pendingFollow;
        return this;
    }

    /**
     * Get pendingFollow
     * @return pendingFollow
     **/
    @Nullable
    @JsonProperty(JSON_PROPERTY_PENDING_FOLLOW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Boolean getPendingFollow() {
        return pendingFollow;
    }

    @JsonProperty(JSON_PROPERTY_PENDING_FOLLOW)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPendingFollow(Boolean pendingFollow) {
        this.pendingFollow = pendingFollow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UsersFollowingCreateResponseData usersFollowingCreateResponseData = (UsersFollowingCreateResponseData) o;
        return Objects.equals(this.following, usersFollowingCreateResponseData.following) &&
            Objects.equals(this.pendingFollow, usersFollowingCreateResponseData.pendingFollow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(following, pendingFollow);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UsersFollowingCreateResponseData {\n");
        sb.append("    following: ").append(toIndentedString(following)).append("\n");
        sb.append("    pendingFollow: ").append(toIndentedString(pendingFollow)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
