/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.UserComplianceSchemaUser;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UserTakedownComplianceSchema
 */
@JsonPropertyOrder({
  UserTakedownComplianceSchema.JSON_PROPERTY_EVENT_AT,
  UserTakedownComplianceSchema.JSON_PROPERTY_USER,
  UserTakedownComplianceSchema.JSON_PROPERTY_WITHHELD_IN_COUNTRIES
})
@JsonTypeName("UserTakedownComplianceSchema")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UserTakedownComplianceSchema {
    public static final String JSON_PROPERTY_EVENT_AT = "event_at";
    private OffsetDateTime eventAt;

    public static final String JSON_PROPERTY_USER = "user";
    private UserComplianceSchemaUser user;

    public static final String JSON_PROPERTY_WITHHELD_IN_COUNTRIES = "withheld_in_countries";
    private List<String> withheldInCountries = new ArrayList<>();

    public UserTakedownComplianceSchema(OffsetDateTime eventAt, UserComplianceSchemaUser user, List<String> withheldInCountries) {
        this.eventAt = eventAt;
        this.user = user;
        this.withheldInCountries = withheldInCountries;
    }

    public UserTakedownComplianceSchema eventAt(OffsetDateTime eventAt) {
        this.eventAt = eventAt;
        return this;
    }

    /**
     * Event time.
     * @return eventAt
     **/
    @NotNull
    @JsonProperty(JSON_PROPERTY_EVENT_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public OffsetDateTime getEventAt() {
        return eventAt;
    }

    @JsonProperty(JSON_PROPERTY_EVENT_AT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
    public void setEventAt(OffsetDateTime eventAt) {
        this.eventAt = eventAt;
    }

    public UserTakedownComplianceSchema user(UserComplianceSchemaUser user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     * @return user
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchemaUser getUser() {
        return user;
    }

    @JsonProperty(JSON_PROPERTY_USER)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUser(UserComplianceSchemaUser user) {
        this.user = user;
    }

    public UserTakedownComplianceSchema withheldInCountries(List<String> withheldInCountries) {
        this.withheldInCountries = withheldInCountries;
        return this;
    }

    public UserTakedownComplianceSchema addWithheldInCountriesItem(String withheldInCountriesItem) {
        this.withheldInCountries.add(withheldInCountriesItem);
        return this;
    }

    /**
     * Get withheldInCountries
     * @return withheldInCountries
     **/
    @NotNull
    @Size(min=1)
    @JsonProperty(JSON_PROPERTY_WITHHELD_IN_COUNTRIES)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public List<String> getWithheldInCountries() {
        return withheldInCountries;
    }

    @JsonProperty(JSON_PROPERTY_WITHHELD_IN_COUNTRIES)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setWithheldInCountries(List<String> withheldInCountries) {
        this.withheldInCountries = withheldInCountries;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserTakedownComplianceSchema userTakedownComplianceSchema = (UserTakedownComplianceSchema) o;
        return Objects.equals(this.eventAt, userTakedownComplianceSchema.eventAt) &&
            Objects.equals(this.user, userTakedownComplianceSchema.user) &&
            Objects.equals(this.withheldInCountries, userTakedownComplianceSchema.withheldInCountries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(eventAt, user, withheldInCountries);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserTakedownComplianceSchema {\n");
        sb.append("    eventAt: ").append(toIndentedString(eventAt)).append("\n");
        sb.append("    user: ").append(toIndentedString(user)).append("\n");
        sb.append("    withheldInCountries: ").append(toIndentedString(withheldInCountries)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
