/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.UserComplianceSchema;
import example.micronaut.model.UserDeleteComplianceSchema;
import example.micronaut.model.UserProfileModificationComplianceSchema;
import example.micronaut.model.UserProfileModificationObjectSchema;
import example.micronaut.model.UserProtectComplianceSchema;
import example.micronaut.model.UserScrubGeoObjectSchema;
import example.micronaut.model.UserScrubGeoSchema;
import example.micronaut.model.UserSuspendComplianceSchema;
import example.micronaut.model.UserTakedownComplianceSchema;
import example.micronaut.model.UserUndeleteComplianceSchema;
import example.micronaut.model.UserUnprotectComplianceSchema;
import example.micronaut.model.UserUnsuspendComplianceSchema;
import example.micronaut.model.UserWithheldComplianceSchema;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * User compliance data.
 */
@JsonPropertyOrder({
  UserComplianceData.JSON_PROPERTY_USER_PROTECT,
  UserComplianceData.JSON_PROPERTY_USER_UNPROTECT,
  UserComplianceData.JSON_PROPERTY_USER_DELETE,
  UserComplianceData.JSON_PROPERTY_USER_UNDELETE,
  UserComplianceData.JSON_PROPERTY_USER_SUSPEND,
  UserComplianceData.JSON_PROPERTY_USER_UNSUSPEND,
  UserComplianceData.JSON_PROPERTY_USER_WITHHELD,
  UserComplianceData.JSON_PROPERTY_SCRUB_GEO,
  UserComplianceData.JSON_PROPERTY_USER_PROFILE_MODIFICATION
})
@JsonTypeName("UserComplianceData")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UserComplianceData {
    public static final String JSON_PROPERTY_USER_PROTECT = "user_protect";
    private UserComplianceSchema userProtect;

    public static final String JSON_PROPERTY_USER_UNPROTECT = "user_unprotect";
    private UserComplianceSchema userUnprotect;

    public static final String JSON_PROPERTY_USER_DELETE = "user_delete";
    private UserComplianceSchema userDelete;

    public static final String JSON_PROPERTY_USER_UNDELETE = "user_undelete";
    private UserComplianceSchema userUndelete;

    public static final String JSON_PROPERTY_USER_SUSPEND = "user_suspend";
    private UserComplianceSchema userSuspend;

    public static final String JSON_PROPERTY_USER_UNSUSPEND = "user_unsuspend";
    private UserComplianceSchema userUnsuspend;

    public static final String JSON_PROPERTY_USER_WITHHELD = "user_withheld";
    private UserTakedownComplianceSchema userWithheld;

    public static final String JSON_PROPERTY_SCRUB_GEO = "scrub_geo";
    private UserScrubGeoObjectSchema scrubGeo;

    public static final String JSON_PROPERTY_USER_PROFILE_MODIFICATION = "user_profile_modification";
    private UserProfileModificationObjectSchema userProfileModification;

    public UserComplianceData(UserComplianceSchema userProtect, UserComplianceSchema userUnprotect, UserComplianceSchema userDelete, UserComplianceSchema userUndelete, UserComplianceSchema userSuspend, UserComplianceSchema userUnsuspend, UserTakedownComplianceSchema userWithheld, UserScrubGeoObjectSchema scrubGeo, UserProfileModificationObjectSchema userProfileModification) {
        this.userProtect = userProtect;
        this.userUnprotect = userUnprotect;
        this.userDelete = userDelete;
        this.userUndelete = userUndelete;
        this.userSuspend = userSuspend;
        this.userUnsuspend = userUnsuspend;
        this.userWithheld = userWithheld;
        this.scrubGeo = scrubGeo;
        this.userProfileModification = userProfileModification;
    }

    public UserComplianceData userProtect(UserComplianceSchema userProtect) {
        this.userProtect = userProtect;
        return this;
    }

    /**
     * Get userProtect
     * @return userProtect
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_PROTECT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserProtect() {
        return userProtect;
    }

    @JsonProperty(JSON_PROPERTY_USER_PROTECT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserProtect(UserComplianceSchema userProtect) {
        this.userProtect = userProtect;
    }

    public UserComplianceData userUnprotect(UserComplianceSchema userUnprotect) {
        this.userUnprotect = userUnprotect;
        return this;
    }

    /**
     * Get userUnprotect
     * @return userUnprotect
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_UNPROTECT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserUnprotect() {
        return userUnprotect;
    }

    @JsonProperty(JSON_PROPERTY_USER_UNPROTECT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserUnprotect(UserComplianceSchema userUnprotect) {
        this.userUnprotect = userUnprotect;
    }

    public UserComplianceData userDelete(UserComplianceSchema userDelete) {
        this.userDelete = userDelete;
        return this;
    }

    /**
     * Get userDelete
     * @return userDelete
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_DELETE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserDelete() {
        return userDelete;
    }

    @JsonProperty(JSON_PROPERTY_USER_DELETE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserDelete(UserComplianceSchema userDelete) {
        this.userDelete = userDelete;
    }

    public UserComplianceData userUndelete(UserComplianceSchema userUndelete) {
        this.userUndelete = userUndelete;
        return this;
    }

    /**
     * Get userUndelete
     * @return userUndelete
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_UNDELETE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserUndelete() {
        return userUndelete;
    }

    @JsonProperty(JSON_PROPERTY_USER_UNDELETE)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserUndelete(UserComplianceSchema userUndelete) {
        this.userUndelete = userUndelete;
    }

    public UserComplianceData userSuspend(UserComplianceSchema userSuspend) {
        this.userSuspend = userSuspend;
        return this;
    }

    /**
     * Get userSuspend
     * @return userSuspend
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_SUSPEND)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserSuspend() {
        return userSuspend;
    }

    @JsonProperty(JSON_PROPERTY_USER_SUSPEND)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserSuspend(UserComplianceSchema userSuspend) {
        this.userSuspend = userSuspend;
    }

    public UserComplianceData userUnsuspend(UserComplianceSchema userUnsuspend) {
        this.userUnsuspend = userUnsuspend;
        return this;
    }

    /**
     * Get userUnsuspend
     * @return userUnsuspend
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_UNSUSPEND)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserUnsuspend() {
        return userUnsuspend;
    }

    @JsonProperty(JSON_PROPERTY_USER_UNSUSPEND)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserUnsuspend(UserComplianceSchema userUnsuspend) {
        this.userUnsuspend = userUnsuspend;
    }

    public UserComplianceData userWithheld(UserTakedownComplianceSchema userWithheld) {
        this.userWithheld = userWithheld;
        return this;
    }

    /**
     * Get userWithheld
     * @return userWithheld
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_WITHHELD)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserTakedownComplianceSchema getUserWithheld() {
        return userWithheld;
    }

    @JsonProperty(JSON_PROPERTY_USER_WITHHELD)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserWithheld(UserTakedownComplianceSchema userWithheld) {
        this.userWithheld = userWithheld;
    }

    public UserComplianceData scrubGeo(UserScrubGeoObjectSchema scrubGeo) {
        this.scrubGeo = scrubGeo;
        return this;
    }

    /**
     * Get scrubGeo
     * @return scrubGeo
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_SCRUB_GEO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserScrubGeoObjectSchema getScrubGeo() {
        return scrubGeo;
    }

    @JsonProperty(JSON_PROPERTY_SCRUB_GEO)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setScrubGeo(UserScrubGeoObjectSchema scrubGeo) {
        this.scrubGeo = scrubGeo;
    }

    public UserComplianceData userProfileModification(UserProfileModificationObjectSchema userProfileModification) {
        this.userProfileModification = userProfileModification;
        return this;
    }

    /**
     * Get userProfileModification
     * @return userProfileModification
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_PROFILE_MODIFICATION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserProfileModificationObjectSchema getUserProfileModification() {
        return userProfileModification;
    }

    @JsonProperty(JSON_PROPERTY_USER_PROFILE_MODIFICATION)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserProfileModification(UserProfileModificationObjectSchema userProfileModification) {
        this.userProfileModification = userProfileModification;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserComplianceData userComplianceData = (UserComplianceData) o;
        return Objects.equals(this.userProtect, userComplianceData.userProtect) &&
            Objects.equals(this.userUnprotect, userComplianceData.userUnprotect) &&
            Objects.equals(this.userDelete, userComplianceData.userDelete) &&
            Objects.equals(this.userUndelete, userComplianceData.userUndelete) &&
            Objects.equals(this.userSuspend, userComplianceData.userSuspend) &&
            Objects.equals(this.userUnsuspend, userComplianceData.userUnsuspend) &&
            Objects.equals(this.userWithheld, userComplianceData.userWithheld) &&
            Objects.equals(this.scrubGeo, userComplianceData.scrubGeo) &&
            Objects.equals(this.userProfileModification, userComplianceData.userProfileModification);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userProtect, userUnprotect, userDelete, userUndelete, userSuspend, userUnsuspend, userWithheld, scrubGeo, userProfileModification);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserComplianceData {\n");
        sb.append("    userProtect: ").append(toIndentedString(userProtect)).append("\n");
        sb.append("    userUnprotect: ").append(toIndentedString(userUnprotect)).append("\n");
        sb.append("    userDelete: ").append(toIndentedString(userDelete)).append("\n");
        sb.append("    userUndelete: ").append(toIndentedString(userUndelete)).append("\n");
        sb.append("    userSuspend: ").append(toIndentedString(userSuspend)).append("\n");
        sb.append("    userUnsuspend: ").append(toIndentedString(userUnsuspend)).append("\n");
        sb.append("    userWithheld: ").append(toIndentedString(userWithheld)).append("\n");
        sb.append("    scrubGeo: ").append(toIndentedString(scrubGeo)).append("\n");
        sb.append("    userProfileModification: ").append(toIndentedString(userProfileModification)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
