/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.UserComplianceSchema;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UserProtectComplianceSchema
 */
@JsonPropertyOrder({
  UserProtectComplianceSchema.JSON_PROPERTY_USER_PROTECT
})
@JsonTypeName("UserProtectComplianceSchema")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UserProtectComplianceSchema {
    public static final String JSON_PROPERTY_USER_PROTECT = "user_protect";
    private UserComplianceSchema userProtect;

    public UserProtectComplianceSchema(UserComplianceSchema userProtect) {
        this.userProtect = userProtect;
    }

    public UserProtectComplianceSchema userProtect(UserComplianceSchema userProtect) {
        this.userProtect = userProtect;
        return this;
    }

    /**
     * Get userProtect
     * @return userProtect
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_PROTECT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserProtect() {
        return userProtect;
    }

    @JsonProperty(JSON_PROPERTY_USER_PROTECT)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserProtect(UserComplianceSchema userProtect) {
        this.userProtect = userProtect;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserProtectComplianceSchema userProtectComplianceSchema = (UserProtectComplianceSchema) o;
        return Objects.equals(this.userProtect, userProtectComplianceSchema.userProtect);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userProtect);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserProtectComplianceSchema {\n");
        sb.append("    userProtect: ").append(toIndentedString(userProtect)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
