/*
 * Twitter API v2
 * Twitter API v2 available endpoints
 *
 * The version of the OpenAPI document: 2.55
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package example.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import example.micronaut.model.UserComplianceSchema;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * UserUnsuspendComplianceSchema
 */
@JsonPropertyOrder({
  UserUnsuspendComplianceSchema.JSON_PROPERTY_USER_UNSUSPEND
})
@JsonTypeName("UserUnsuspendComplianceSchema")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2022-11-05T03:44:30.749524299+01:00[Europe/Berlin]")
@Introspected
public class UserUnsuspendComplianceSchema {
    public static final String JSON_PROPERTY_USER_UNSUSPEND = "user_unsuspend";
    private UserComplianceSchema userUnsuspend;

    public UserUnsuspendComplianceSchema(UserComplianceSchema userUnsuspend) {
        this.userUnsuspend = userUnsuspend;
    }

    public UserUnsuspendComplianceSchema userUnsuspend(UserComplianceSchema userUnsuspend) {
        this.userUnsuspend = userUnsuspend;
        return this;
    }

    /**
     * Get userUnsuspend
     * @return userUnsuspend
     **/
    @Valid
    @NotNull
    @JsonProperty(JSON_PROPERTY_USER_UNSUSPEND)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public UserComplianceSchema getUserUnsuspend() {
        return userUnsuspend;
    }

    @JsonProperty(JSON_PROPERTY_USER_UNSUSPEND)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setUserUnsuspend(UserComplianceSchema userUnsuspend) {
        this.userUnsuspend = userUnsuspend;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserUnsuspendComplianceSchema userUnsuspendComplianceSchema = (UserUnsuspendComplianceSchema) o;
        return Objects.equals(this.userUnsuspend, userUnsuspendComplianceSchema.userUnsuspend);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userUnsuspend);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UserUnsuspendComplianceSchema {\n");
        sb.append("    userUnsuspend: ").append(toIndentedString(userUnsuspend)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
