micronaut:
  application:
    name: openapi-micronaut
  server:
    port: 8080
  security:
    oauth2:
      clients:
        twitter:
          client-id: '${TWITTER_AUTH_CLIENT_ID:}'
          client-secret: '${TWITTER_AUTH_CLIENT_SECRET:}'
          client-credentials:
            service-id-regex: '.*'
            uri-regex: 'api.twitter.com/.*'
          token:
            url: "${openapi-micronaut-client-base-path:}oauth2/token"
            auth-method: "client_secret_basic" 